### ISSUE TITLE
Problems with rendering in modal box

### ISSUE THREAD

**Issue by stalehard** [phuoc-ng/react-pdf-viewer#105]
Thanks for your work!
I have problems with using library in modal box: 
- Search input field is not interactive  
![Screenshot from 2020-04-13 16-18-13](https://user-images.githubusercontent.com/7106940/79120100-12656e80-7da3-11ea-920f-373e59a17b2d.png)

- Print mode captures unnecessary areas
![Screenshot from 2020-04-13 16-21-51](https://user-images.githubusercontent.com/7106940/79120166-417be000-7da3-11ea-820d-2421c4dae558.png)

**Comment by phuoc-ng** [comment]
I will add an example to help about the printing issue.

**Comment by phuoc-ng** [comment]
@stalehard 
Here is the [Hide unnecessary elements when printing a document](https://react-pdf-viewer.dev/examples/hide-unnecessary-elements-when-printing-a-document) example.

**Comment by phuoc-ng** [comment]
@stalehard The search box in the example works as usual.

**Comment by stalehard** [comment]
Thanks for the support!
I will check CSS rules for conflicts with the input field

**Comment by phuoc-ng** [comment]
@stalehard This example might be useful as well https://react-pdf-viewer.dev/examples/preview-a-document-inside-a-modal
