### ISSUE TITLE
Fuzzy texts when react-pdf-viewer renders and show pdf file compared to the original pdf file.

### ISSUE THREAD

**Issue by wonjunkang** [phuoc-ng/react-pdf-viewer#106]
Hi @phuoc-ng, 
I've been testing with react libraries that show pdf file and I like your library the best.
But I see some fuzziness on the texts when pdf file is rendered through the library. 

This is the original pdf file if I download it through your toolbar. 
<img width="1135" alt="Screen Shot 2020-04-13 at 12 15 12 PM" src="https://user-images.githubusercontent.com/58698642/79138078-dcfc5900-7d81-11ea-8705-7aee920f161f.png">

This is the pdf rendered by the library and I see the fuzzy texts here if you take a look at it closely. 
What's weird about it is that if you look at the zooming out or zooming in icon on the toolbar, it also seems fuzziness. 

![Screen Shot 2020-04-13 at 12 14 50 PM](https://user-images.githubusercontent.com/58698642/79138101-eab1de80-7d81-11ea-8d70-114fd27bcec7.png)

When I zoom in using the trackpad on my laptop dragging my fingers away from each other in the browser, zooming icons become sharp and clear. So they may share the same problem I think?

![Screen Shot 2020-04-13 at 12 14 42 PM](https://user-images.githubusercontent.com/58698642/79138559-b68aed80-7d82-11ea-9922-c83f7ad223df.png)

Could you help me out how I can make this fuzziness go away? 
Once this is fixed, we would like to use this library in our production. 
Thanks :)

**Comment by JSurquin** [comment]
Excuse me to response to the place of @phuoc-ng , actually pdf pages generates in Canvas (cause fuzzy) , @phuoc-ng is already make a svg layer (fix fuzzy effect) Svg layer will be soon available in 1.5.0 , you Can test this in my codesanbox or pull master branch and create a sample for test in codesanbox

**Comment by phuoc-ng** [comment]
@wonjunkang @JSurquin 
v1.5.0 was released. You can try to replace the canvas with SVG layer:
https://react-pdf-viewer.dev/examples/replace-the-canvas-with-svg-layer

@wonjunkang Can you give me the pdf, so I can try it on my local?

**Comment by wonjunkang** [comment]
Hi Phuoc-ng, thanks for your quick reply. I'll try it with the new version. Here is the pdf I'm testing with. Thank you so much![
[bb93c178-ef53-4756-810e-b7f7fd0839b7.pdf](https://github.com/phuoc-ng/react-pdf-viewer/files/4476933/bb93c178-ef53-4756-810e-b7f7fd0839b7.pdf)
](url)

**Comment by wonjunkang** [comment]
Hi @phuoc-ng, the fizzy font is fixed now. Thanks!
I see that fonts seeps through the background color which is not white in our container..
Is it possible to make the pdf document's(only the paper itself) background set as white when getting rendered?

**Comment by phuoc-ng** [comment]
@wonjunkang Can you give me a screenshot of the container, so I can imagine the situation and give you the solution?

**Comment by wonjunkang** [comment]
@phuoc-ng 
yeah so this is default and it takes the background color of the outside Worker component.
<img width="1197" alt="Screen Shot 2020-04-15 at 7 23 52 PM" src="https://user-images.githubusercontent.com/58698642/79398752-63b26100-7f4f-11ea-8843-a48f66cd61cd.png">

This is when I changed the background of the div that has class "viewer-layout-main" to white. 
What I want is just the paper to be white but instead the space between pages are also gets affected(become white also.) 

<img width="1094" alt="Screen Shot 2020-04-15 at 7 27 58 PM" src="https://user-images.githubusercontent.com/58698642/79398822-98beb380-7f4f-11ea-9028-0a8b26102359.png">
 
Is there a way I can change this properly? 

And could you give me your email so that I can talk about price for commercial usage?
Thanks

**Comment by phuoc-ng** [comment]
@wonjunkang 
I just try to set a custom background color for `viewer-layout-main`

~~~ css
.viewer-layout-main {
  background: #ccc;
}
~~~

and there is no white area between pages:

<img width="1056" alt="Screen Shot 2020-04-16 at 23 02 58" src="https://user-images.githubusercontent.com/57786711/79479146-88353880-8036-11ea-9de5-da079e42879d.png">

**Comment by wonjunkang** [comment]
Thanks this works!

**Comment by eduardofcbg** [comment]
Hello. Why has this issue been closed? The SVG layer prevents the fuzzy text, but the issue persists in the Canvas layer. Is this issue fixable in the Canvas layer? I'm asking this because the SVG layer is considered experimental by the devs of pdfjs.
Thanks!

**Comment by phuoc-ng** [comment]
I re-open the #116 to track!

**Comment by EyobTem** [comment]
When reports load the text appears choppy and in some cases completely unreadable in react js pdf viewer

**Comment by pateljoel** [comment]
@phuocng Has there been any progress on this, the text looks very unreadable on my screen.
