### ISSUE TITLE
Support for non-latin characters

### ISSUE THREAD

**Issue by hamidfzm** [phuoc-ng/react-pdf-viewer#107]
There is a problem with displaying non-latin characters. Using cmaps in pdfjs will fix this issue. But how should we apply cmaps for worker?

![Screenshot from 2020-04-14 00-41-45](https://user-images.githubusercontent.com/5591800/79156857-da811a00-7de8-11ea-9bb4-b3478800bb6d.png)

**Comment by phuoc-ng** [comment]
@hamidfzm Can you let me know how you pass the cmaps to current viewer?
Since I don't support it yet.

**Comment by phuoc-ng** [comment]
Supporting cmap option will be available in the next version 1.7.0.

**Comment by phuoc-ng** [comment]
Done.

~~~ javascript
import Viewer, { CharacterMap } from '@phuocng/react-pdf-viewer';

const characterMap: CharacterMap = {
    isCompressed: true,
    url: 'https://unpkg.com/pdfjs-dist@2.4.456/cmaps/',
};

<Viewer
    characterMap={characterMap}
    fileUrl='/path/to/document.pdf'
/>
~~~

**Comment by phuoc-ng** [comment]
@hamidfzm 
Done. v1.7.0 is [released](https://react-pdf-viewer.dev/updates).
You can upgrade to the latest version to use this feature.
