### ISSUE TITLE
Tooltip position is only correct when window hasn't scrolled

### ISSUE THREAD

**Issue by christophhapple** [phuoc-ng/react-pdf-viewer#115]
Hi @phuoc-ng 

The tooltip for the buttons is appended right before `</body>` and then positioned absolutely. This makes it relative to the `<html>` element (assuming `<body>` has `position: static;` or not set at all).
Given that the top and left values stay the same, the tooltip position should not change either, even when scrolling.

In the [demo](https://react-pdf-viewer.dev/), the value for top stays the same, even when scrolling.
For me, however, the top and left values change when scrolling.

No scroll - top: 404px
![tooltip_pos-correct](https://user-images.githubusercontent.com/18899363/79871296-6e07ab80-83e4-11ea-8f44-8d3459f7f648.png)

Having scrolled down a bit - top: 285px
![tooltip_pos-incorrect](https://user-images.githubusercontent.com/18899363/79871317-75c75000-83e4-11ea-98b7-74a0c25acb4c.png)

Why does this happen? Does the calculation of the position require some kind of root element or some other structure to be present to work?
Calculation happens somewhere around here:
/react-pdf-viewer/cjs/react-pdf-viewer.js, l. 400

I tried removing all the other JS on my page, but no success.

Thanks for your help and all your work - have a nice day!

**Comment by phuoc-ng** [comment]
@christophhapple 
Thanks for reporting the issue. I can confirm that it's a bug and I can reproduce the issue locally

<img width="1082" alt="Screen Shot 2020-04-22 at 21 05 49" src="https://user-images.githubusercontent.com/57786711/79992004-21ec6200-84dd-11ea-83cb-f3f096b3b748.png">

I'll ping you when it's fixed.

**Comment by phuoc-ng** [comment]
@christophhapple It's fixed 

![fix-position](https://user-images.githubusercontent.com/57786711/80107190-f9c83600-85a4-11ea-9ee1-3d3220b78dd3.gif)

It will come with the next v1.6.0.

**Comment by phuoc-ng** [comment]
@christophhapple The v1.6.0 is just [released](https://react-pdf-viewer.dev/updates). Please upgrade.

**Comment by christophhapple** [comment]
@phuoc-ng Great stuff, thanks so much!
