### ISSUE TITLE
Blurry pdf

### ISSUE THREAD

**Issue by eduardofcbg** [phuoc-ng/react-pdf-viewer#116]
The rendered pdfs look blurry, compared to pdfjs

- react-pdf-viewer

<img width="257" alt="image" src="https://user-images.githubusercontent.com/7091654/79928978-4e9c6d00-843c-11ea-8f6b-b5514a88405f.png">

- pdfjs

<img width="267" alt="image" src="https://user-images.githubusercontent.com/7091654/79929008-64119700-843c-11ea-9886-d58e72e148fb.png">

Both same resolution on retina MacBook Air.
Thanks!

**Comment by eduardofcbg** [comment]
Repeated issue from GH-26

**Comment by eduardofcbg** [comment]
Duplicate of  #106

**Comment by eduardofcbg** [comment]
Thanks for reopening, this is indeed a bug. Any clue on what could be causing this? I could contribute.

**Comment by phuoc-ng** [comment]
@eduardofcbg @wonjunkang 

It will be fixed and comes with the next version. I'll ping you when the PR is ready!

Here is how it looks like (click the thumbnails to see the differences).

_Current_
<img width="1049" alt="Screen Shot 2020-04-22 at 10 17 40" src="https://user-images.githubusercontent.com/57786711/79936818-8cbc7f80-8482-11ea-88b2-ad01a66c8ace.png">

_Fix_
<img width="1062" alt="Screen Shot 2020-04-22 at 10 15 23" src="https://user-images.githubusercontent.com/57786711/79936653-33ece700-8482-11ea-816d-6de5d95469cf.png">

**Comment by eduardofcbg** [comment]
Great!

**Comment by wonjunkang** [comment]
Just out curiosity, may I ask how you fixed this? what was it that was causing this?

**Comment by phuoc-ng** [comment]
@eduardofcbg @wonjunkang This issue is fixed in the PR #119 

<img width="1052" alt="Screen Shot 2020-04-22 at 20 50 34" src="https://user-images.githubusercontent.com/57786711/79990180-eea8d380-84da-11ea-932a-13119861ebb5.png">

**Comment by phuoc-ng** [comment]
@eduardofcbg @wonjunkang 
Please upgrade to the latest version 1.6.0 which fixes the issue.
See the full change log [here](https://react-pdf-viewer.dev/updates).
