### ISSUE TITLE
Dynamically load pdfs by changing "fileUrl"

### ISSUE THREAD

**Issue by r2o3k** [phuoc-ng/react-pdf-viewer#121]
Not sure if this is possible, but it would be great to dynamically load different pdfs by changing the "fileUrl" property instead of using the file open button.

**Comment by phuoc-ng** [comment]
@r2o3k You can treat the \`fileUrl\` as your component's state.

**Comment by sk1794** [comment]
> @r2o3k You can treat the `fileUrl` as your component's state.

i tried fileurl as state, and after the state gets change it doesn't update the ui, it shows the same ui

**Comment by phuoc-ng** [comment]
@r2o3k @sk1794 
I am sorry. I have just fixed that. From the next v1.6.0, we can control the `fileUrl` option from outside.

_Demo_:

![change-url](https://user-images.githubusercontent.com/57786711/80794848-18da4f80-8bc5-11ea-8e1a-8269fea2f450.gif)

**Comment by sk1794** [comment]
> @r2o3k @sk1794
> I am sorry. I have just fixed that in PR #157. From the next v1.6.0, we can control the `fileUrl` option from outside.
> 
> _Demo_:
> 
> ![change-url](https://user-images.githubusercontent.com/57786711/80794848-18da4f80-8bc5-11ea-8e1a-8269fea2f450.gif)

hey, thanks a lot, it was high priority for me to change the url's dynamically, when will i get the latest update?

**Comment by phuoc-ng** [comment]
@sk1794 I'll ping here when it's available, hopefully in the next 1-2 days.

**Comment by sk1794** [comment]
> @sk1794 I'll ping here when it's available, hopefully in the next 1-2 days.

hi, any update on this version release?

**Comment by phuoc-ng** [comment]
@r2o3k @sk1794 
Please upgrade to the latest version 1.6.0 which fixes the issue.
See the full change log [here](https://react-pdf-viewer.dev/updates).
