### ISSUE TITLE
Click to open link on pdf when link not hyperlink

### ISSUE THREAD

**Issue by JSurquin** [phuoc-ng/react-pdf-viewer#129]
Hello, I did a test by creating a simple example of pdf without hyperlink, I put https://google.fr and check it in the pdf reader, the link is not clickable, however, if the link is in hyperlink via libreoffice or other, the link is clickable :)

I did the same test with the native pdf reader of google chrome and whether in hyperlink or not, it detects that it is a link and allows to be able to click on it

Would it be possible to think of this scenario?

Indeed, the standard is respected but I do not think that the agents (I work for a company recognized as a training organization / education) will have the idea of ​​creating hyperlinks while they make their pdf

I could put a very quick example on a codesanbox or share the two pdf to dissociate the two cases, if necessary :)

Thank you again for taking the time to read me.

**Comment by phuoc-ng** [comment]
@JSurquin 
Thanks for reaching out. I am rewriting the entire annotation layers (see #100) which also cover your use case.
Can you upload the sample document here and I'll ping you when there's a PR to fix that.

**Comment by JSurquin** [comment]
thanks for the quick response :)

[aSamplePdf_With_Hyperlink.pdf](https://github.com/phuoc-ng/react-pdf-viewer/files/4547107/aSamplePdf_With_Hyperlink.pdf)

[aSamplePdf_Without_Hyperlink.pdf](https://github.com/phuoc-ng/react-pdf-viewer/files/4547108/aSamplePdf_Without_Hyperlink.pdf)

**Comment by phuoc-ng** [comment]
@JSurquin 
It was fixed in PR #144 and will be available in in the next 1.6.0.

_Demo_

![link](https://user-images.githubusercontent.com/57786711/80716072-67cea900-8b21-11ea-8300-f862fc4a669a.gif)

**Comment by phuoc-ng** [comment]
@JSurquin Please upgrade to the latest version [1.6.0](https://react-pdf-viewer.dev/updates) which fixes the issue.

**Comment by JSurquin** [comment]
I update to 1.6.0 and I always have the same behavior :/ 

with the file without hyperlink

**Comment by JSurquin** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/33385043/81077534-602a4e00-8eed-11ea-9888-5c59f073c790.gif)

**Comment by phuoc-ng** [comment]
I just download the document, and drag drop it to https://react-pdf-viewer.dev, and it works as expected. You can try to see.

Does it work if you place the viewer in the page, not inside the modal?

**Comment by JSurquin** [comment]
https://codesandbox.io/s/react-pdf-viewer-160-with-sample-pdf-without-hyperlink-added-kevqi?file=/src/App.js

I created a codesanbox to confirm that without obstructing css rules, it is still the case
I tested without the modal completely and I tested without the SVG layer but with the canvas (which by the way, is great, a very good job)

In fact, on the native pdf reader of chrome or firefox, when a pdf has been generated with a line containing an http / https link but without using a "hyperlink", the pdf reader recognizes it anyway and offers the link as clickable

**Comment by JSurquin** [comment]
As I told you above, I work for a training center, so the teachers creating the pdf could actually use hyperlinks in the document but what do you want? :p

This type of profile is not comfortable with IT and I think this feature is interesting anyway, in addition to the excellent work already provided :)

**Comment by phuoc-ng** [comment]
@JSurquin I am clear now.

- The hyper link is parsed and rendered as a link annotation, and it's a standard PDF format.
The previous version v1.5.0 doesn't support that, and the latest fixes the issue.

- Now, for the text which isn't actually a hyperlink, but indeed should be treated as a link.
In order to support that, we have to use an external library to parse the text, and turn the link-like text into hyperlinks.

There're some libraries such as 
* https://github.com/Soapbox/linkifyjs
* http://markdown-it.github.io/linkify-it/

I'll try to create an example for you using one of these libraries with the viewer.

**Comment by phuoc-ng** [comment]
@JSurquin Here is a [working example](https://github.com/phuoc-ng/react-pdf-viewer/tree/master/demo/linkify).

_Demo_

(take a look at the bottom of the screenshot below, and you'll see that the text is replaced with a link)

<img width="955" alt="Screen Shot 2020-05-05 at 22 49 00" src="https://user-images.githubusercontent.com/57786711/81087291-b914d900-8f23-11ea-9a25-078653cfbf94.png">

**Comment by JSurquin** [comment]
Awesome, it works well and it's the perfect behavior
Thank you again, subject closed :)

**Comment by phuoc-ng** [comment]
Great. Let me know if you have any questions or suggestions.
