### ISSUE TITLE
search navigation

### ISSUE THREAD

**Issue by sk1794** [phuoc-ng/react-pdf-viewer#165]
i am facing issue on search navigation, it doesn't navigate to the word i searched, i have to scroll up or down to show the highlighted text

![Annotation 2020-05-13 145849](https://user-images.githubusercontent.com/30054578/81795900-51195080-952a-11ea-9e43-fa789571f96f.png)

**Comment by phuoc-ng** [comment]
Can you drag and drop the document to the viewer at [official website](https://react-pdf-viewer.dev) and let me know it works or not?
If it doesn't, please attach the document here.

**Comment by sk1794** [comment]
> Can you drag and drop the document to the viewer at [official website](https://react-pdf-viewer.dev) and let me know it works or not?
> If it doesn't, please attach the document here.

it doesn't work
[20170524112043A00000000_001.pdf](https://github.com/phuoc-ng/react-pdf-viewer/files/4627267/20170524112043A00000000_001.pdf)


here is the pdf

**Comment by sk1794** [comment]
> > Can you drag and drop the document to the viewer at [official website](https://react-pdf-viewer.dev) and let me know it works or not?
> > If it doesn't, please attach the document here.
> 
> it doesn't work
> [20170524112043A00000000_001.pdf](https://github.com/phuoc-ng/react-pdf-viewer/files/4627267)
> 
> here is the pdf, search for rosemarie

hi, any update on this?

**Comment by phuoc-ng** [comment]
@sk1794 I can confirm that it's a bug. I'll try to fix and release it with 1.7.0. I will ping you when there's any update.

**Comment by sk1794** [comment]
> @sk1794 I can confirm that it's a bug. I'll try to fix and release it with 1.7.0. I will ping you when there's any update.

hi, any updates on this?

**Comment by phuoc-ng** [comment]
@sk1794 
It was fixed in the latest code. I'll ping you when the v1.7.0 is released.

_Demo 1_

![search](https://user-images.githubusercontent.com/57786711/84589849-b6c76800-ae5b-11ea-8283-b8ff63c98003.gif)

_Demo 2_

![jump](https://user-images.githubusercontent.com/57786711/84589871-ee361480-ae5b-11ea-9c76-23c26eaadfb4.gif)

**Comment by phuoc-ng** [comment]
@sk1794 
v1.7.0 is just [released](https://react-pdf-viewer.dev/updates).
Please upgrade.

**Comment by jkeruzec** [comment]
Is it also possible to have a feature where search is not scrolling ? using an option for instance (scrolling true by default)
Explanation of my case :
I would like to have a display page by page only and scrolling feature is displaying an in between page that is not very beautifull for what I'm trying to do

**Comment by helianthuswhite** [comment]
> @phuoc-ng Is it also possible to have a feature where search is not scrolling ? using an option for instance (scrolling true by default) Explanation of my case : I would like to have a display page by page only and scrolling feature is displaying an in between page that is not very beautifull for what I'm trying to do Highlighted words is enough for me because I have a full display of my page each time.

same for me.
