### ISSUE TITLE
regression

### ISSUE THREAD

**Issue by oumaima1234** [phuoc-ng/react-pdf-viewer#170]
![Capture](https://user-images.githubusercontent.com/27361973/83782856-4157dc80-a690-11ea-8a3d-1ba10a2b4217.PNG)

**Comment by phuoc-ng** [comment]
@oumaima1234 Can you tell me how to reproduce the issue?

**Comment by oumaima1234** [comment]
hello, 
I tried this example from the demo folder, [https://github.com/phuoc-ng/react-pdf-viewer/tree/master/demo/create-react-app] , it was wokring correctly, yesterday, I removed the node-modules folder and the package-lock.json file, then: 
npm install , npm run build, npm start, and I found this issue. 
I'm also using your component to view pdf files in my application and I'm no more able to get a successful build nor compilation. That's why I decided to re-run your example.

**Comment by phuoc-ng** [comment]
@oumaima1234 Please make sure that the pdfjs version used in the `Worker` must be the same as the version of `pdfjs-dist` in the `package.json`.

I recommend to follow the steps:

1. `npm install pdfjs-dist@2.4.456`
2. `npm install @phuocng/react-pdf-viewer@1.6.0`
3. Setup Worker:

```js
<Worker workerUrl="https://unpkg.com/pdfjs-dist@2.4.456/build/pdf.worker.min.js">
...
</Worker>
```

**Comment by phuoc-ng** [comment]
Related to #172

**Comment by oumaima1234** [comment]
hello, thank you for your answer but it still don't work after the updates. I have this issue when trying to build 
![image](https://user-images.githubusercontent.com/27361973/83957246-bc72eb80-a866-11ea-9916-824413be59f4.png)

**Comment by phuoc-ng** [comment]
Here is a working, simplest demo work with [create-react-app](https://github.com/phuoc-ng/react-pdf-viewer/tree/master/demo/create-react-app).

**Comment by oumaima1234** [comment]
Thanks, but problems persist :( 
Can you provide me the node and npm versions that you are using please ? 
Thanks in advance!
![image](https://user-images.githubusercontent.com/27361973/83972251-50809980-a8df-11ea-89ae-13ea856d4c65.png)

**Comment by oumaima1234** [comment]
Hello, The previous error is related to the chrome browser version. 
But, I want to mention that the new version does not support blob files ( it works only with pdf files)

**Comment by phuoc-ng** [comment]
@oumaima1234 So now you can make it work with the latest version (1.6.0)?

> I want to mention that the new version does not support blob file

Can you tell me how to reproduce the issue?
This [example](https://react-pdf-viewer.dev/examples/preview-a-pdf-file-from-base-64) works.

**Comment by phuoc-ng** [comment]
> I want to mention that the new version does not support blob files ( it works only with pdf files)

It was fixed (I think you were using the code from master, and at that time, there was issue with loading/opening file from blob).

Please try the v1.7.0 which is just [released](https://react-pdf-viewer.dev/updates).
