### ISSUE TITLE
Issue when launching the Worker: Unknown action from worker: undefined

### ISSUE THREAD

**Issue by MilesYM** [phuoc-ng/react-pdf-viewer#172]
First time trying to make it work.

I have been following the doc and I believe everything is in order.
Unfortunately, when I'm trying to launch it, I get a an error:

<img width="1435" alt="Screen Shot 2020-06-05 at 6 31 22 PM" src="https://user-images.githubusercontent.com/3511013/83901416-04a4e780-a75b-11ea-9dc6-239a4fd47ce8.png">

Where does this come from? I'm using an absolute url starting with https:// , which works otherwise.
I've been doing a yarn install and yarn upgrade to make sure everything is up to date.

Any help is appreciated.
Thanks

**Comment by MilesYM** [comment]
Ok I found out this is coming from the version of the librairy being incorrect.
I copied and paste it from the doc but it is important to say the version of stated in the link should be the one specified in your packages.json, latest version as of today is:

https://unpkg.com/pdfjs-dist@2.4.456/build/pdf.worker.min.js

Hope this helps.

**Comment by phuoc-ng** [comment]
Thank @MilesYM.
I updated the documentation:

1. Emphasize the [steps](https://react-pdf-viewer.dev/docs/getting-started):
- Step 1: Install `pdfjs-dist` first
- Step 2: Install react-pdf-viewer

2. Add a note in the [setting up the worker](https://react-pdf-viewer.dev/docs/basic-usage) section:

<img width="775" alt="Screen Shot 2020-06-06 at 22 17 39" src="https://user-images.githubusercontent.com/57786711/83947827-9e47c400-a843-11ea-837e-bd276088b973.png">

Now it includes the error message you saw earlier.
