### ISSUE TITLE
Add option to prevent scrolling

### ISSUE THREAD

**Issue by MilesYM** [phuoc-ng/react-pdf-viewer#173]
I would like to remove the ability to scroll and only display one page at a time to force the user to click on next and previous. I want to track when a page is being reviewed (and which one).

Is this possible?
How is this doable?

Thank you.

**Comment by phuoc-ng** [comment]
It was implemented in the latest code, and will be available in the next version (__v1.7.0__).
Here is an [example](https://github.com/phuoc-ng/react-pdf-viewer/blob/master/demo/store-current-page/StoreCurrentPageExample.tsx):

```javascript
import Viewer, { PageChangeEvent } from '@phuocng/react-pdf-viewer';

const handlePageChange = (e: PageChangeEvent) => {
  console.log(`Current page: ${e.currentPage}`);
};

<Viewer
  fileUrl="/path/to/document.pdf"
  onPageChange={handlePageChange}
/>
```

**Comment by MilesYM** [comment]
Thank you, just to understand, if I add onPageChange, you cannot scroll the slides anymore? You have to click on next page and previous page to go from a slide to the other?
Thank you.

**Comment by phuoc-ng** [comment]
No, user can scroll the page as usual, but `onPageChange` will be called as soon as user view/scroll to another page.

I think that option is good enough as it serves the requirement (tracking the page user view).

**Comment by MilesYM** [comment]
Ok thank you.
It would be great to give that option, scrolling is not always the behavior wanted, lots of other (free) plugins give that option by default (but they lack other features).
Thanks anyway.

**Comment by phuoc-ng** [comment]
@MilesYM 
The v1.7.0 is [released](https://react-pdf-viewer.dev/updates).
Please upgrade to the latest version to use [onPageChange](https://react-pdf-viewer.dev/docs/options) event.

**Comment by MilesYM** [comment]
Great thank you so much.
Is there any chance we can remove the option to scroll to force the user to click on next page? I'm looking to track how much time someone is spending on a slide just like what you can do on docsend.
Thank you very much for working with me on the onPageChange! Much appreciated!

**Comment by phuoc-ng** [comment]
@MilesYM 
Can you try the [approach](https://github.com/phuoc-ng/react-pdf-viewer/issues/173#issuecomment-642010387) I suggested above?
