### ISSUE TITLE
I didn't see a way to enable a "Print" tool

### ISSUE THREAD

**Issue by Eric24** [phuoc-ng/react-pdf-viewer#19]

**Comment by phuoc-ng** [comment]
I'll add it to the Roadmap. It's not supported at the moment.

**Comment by Eric24** [comment]
Excellent, thank you. Do you see this as an easy or difficult feature? Do you have any estimate of when it might be added?

**Comment by Eric24** [comment]
Any update on the timing of the print feature? I'm within a few days of making a decision and printing is a critical issue for me.

**Comment by phuoc-ng** [comment]
@Eric24 Stay tuned! The next version 1.2.0 coming in the next week will support printing and a few other improvements.
I'll mention you in the PRs supporting _print_.

**Comment by Eric24** [comment]
Excellent. I look forward to it!

**Comment by phuoc-ng** [comment]
@Eric24 You can see a demo in this [tweet](https://twitter.com/nghuuphuoc/status/1232131786840260608).

(Github doesn't allow to post a mp4, webm files, so I have to make a tweet).

**Comment by Eric24** [comment]
Looks great!

**Comment by Eric24** [comment]
@phuoc-ng - Just checking in to see how the new release is coming.

Also, I'm wondering why you don't use `peerDependencies`, at least for "react" and probably for "react-dom", too?

**Comment by phuoc-ng** [comment]
@Eric24 

* The next version implementation is almost done, I am updating the official website.
You'll see the next version and try/see the print feature in the official website tomorrow, hopefully 👍 

* `react`, `react-dom` are the peer dependencies as you see [here](https://github.com/phuoc-ng/react-pdf-viewer/blob/master/dist/package.json#L26-L29)

**Comment by Eric24** [comment]
Excellent! I look forward to it.

By the way, while there's no absolute right or wrong way, I suggest that `pdfjs-dist` be a "dependency", since it's most likely that it would be internally to `react-pdf-viewer` rather than be something the user of `react-pdf-viewer` is likely to already be using, like `react` and `react-dom`.

**Comment by phuoc-ng** [comment]
That's good point. I would like to update in this release as well.

**Comment by phuoc-ng** [comment]
@Eric24 
* The latest v1.2.0 is released. It supports printing and adds some new options listed [here](https://react-pdf-viewer.dev/updates).
* The official website uses the latest version. You can try to print the document from the _Print_ button in the [homepage](https://react-pdf-viewer.dev/) demo.

Let me know if you see any bugs/suggestions.

**Comment by Eric24** [comment]
Looks great! My plan is for our front-end developer to get the 1.2.0 version from here, integrate and test, and assuming all works well, then license the library. When will the 1.2.0 version be released here?

**Comment by phuoc-ng** [comment]
It was released already on npm:

~~~ console
npm install @phuocng/react-pdf-viewer
~~~

**Comment by phuoc-ng** [comment]
@Eric24 How thing is going? Let me know if you/your front-end engineer need anything from me.

Note that I just released the [v1.4.0](https://react-pdf-viewer.dev/updates) which fixes some print issues:
* Printing doesn't look good if the page size isn't set
* Users see a blank page if they print the web page
