### ISSUE TITLE
Programmatically jump to given page

### ISSUE THREAD

**Issue by phuoc-ng** [phuoc-ng/react-pdf-viewer#20]

**Comment by phuoc-ng** [comment]
Done in v1.4.0.
See the [render props](https://react-pdf-viewer.dev/examples/render-props) example.

**Comment by hleduff** [comment]
Hello,

First of all I want to say, congratulations for your great job on this library! It's cleanly done and feature-rich.

Now my question: is it still possible to jump to a given page in the current version?
The example linked above points to a blank page. I'm not too sure it's exactly what I'm looking for, though.

I see there seems to be a jumpTo/jumpToPage method in page-navigation.js. I would very much like to be able to use it from my component. I have a custom button list where every one points to a specific page number.
