### ISSUE TITLE
Disable buttons toolbar

### ISSUE THREAD

**Issue by caioorg** [phuoc-ng/react-pdf-viewer#206]
Hi @phuoc-ng 

There is a possibility that I could disable specific buttons on the toolbar.

Example: I would not like my users to download or print the PDF I made available to them.

I am aware that if the user really wants to download he will find another means, but it would be nice to have a props that could disable some things.

The way I found it was doing display: none on the button that I don't want, but it has spaces in the middle.

I thank the attention.

**Comment by phuoc-ng** [comment]
@caioorg 
Thank for the suggestion. In the next version, I'll support the way of customizing the button.

For v1.7.0, you can rebuild the toolbar without the `download` button.
See https://react-pdf-viewer.dev/examples/create-a-simple-toolbar

**Comment by caioorg** [comment]
Thank's @phuoc-ng

**Comment by phuoc-ng** [comment]
@caioorg 
Updated: v2.0.1 is released so you can customize anything in the toolbar.
See some examples here https://react-pdf-viewer.dev/plugins/toolbar

<img width="798" alt="Screen Shot 2020-10-24 at 18 43 44" src="https://user-images.githubusercontent.com/57786711/97080889-e451c880-1628-11eb-883f-34e5dc80cba5.png">


Please [upgrade](https://react-pdf-viewer.dev/updates) to 2.0.1.
