### ISSUE TITLE
Setting up fake worker failed: "Cannot read property 'WorkerMessageHandler' of undefined".

### ISSUE THREAD

**Issue by IProdev211** [phuoc-ng/react-pdf-viewer#220]
I run the sample code from https://react-pdf-viewer.dev/examples/preview-a-document-inside-a-modal
But I get the following error:
![Screenshot at Jul 15 03-47-17](https://user-images.githubusercontent.com/54302571/87458910-feedcc00-c64d-11ea-9583-e91e6bda6f98.png)

**Comment by phuoc-ng** [comment]
@IProdev211 As mentioned in https://react-pdf-viewer.dev/docs/basic-usage, please ensure that the pdf.js version installed in your package.json is the same as the one in `Worker` (2.4.456 in the following steps).

1) Install packages:
```console
$ npm install pdfjs-dist@2.4.456
$ npm install @phuocng/react-pdf-viewer@1.7.0
```

2) Setup the worker:
```javascript
import { Worker } from '@phuocng/react-pdf-viewer';

<Worker workerUrl="https://unpkg.com/pdfjs-dist@2.4.456/build/pdf.worker.min.js">
    <!-- The viewer component will be put here -->
    ...
</Worker>
```

**Comment by IProdev211** [comment]
Thank you
