### ISSUE TITLE
How do you change the background color of the menu? Not sure this is possible.

### ISSUE THREAD

**Issue by MilesYM** [phuoc-ng/react-pdf-viewer#233]
Is it possible to change the background color of the menu via some options?

Looking at the doc here: https://react-pdf-viewer.dev/docs/options

I am not able to find anything related to this.

I am talking about this topbar menu:

<img width="1437" alt="Screen Shot 2020-07-20 at 7 14 00 PM" src="https://user-images.githubusercontent.com/3511013/87971399-2d8bfc80-cabd-11ea-8724-8ffdef88cbe0.png">

Thank you

**Comment by phuoc-ng** [comment]
@MilesYM 
You can override the background color of `viewer-layout-toolbar` class:

```css
.viewer-layout-toolbar {
  background-color: #YOUR_COLOR;
}
```

**Comment by MilesYM** [comment]
Thank you

**Comment by phuoc-ng** [comment]
@MilesYM Note that most of elements in the default layout come with a CSS class, so you can customize any element by overriding the associate CSS styles.
