### ISSUE TITLE
Extract component functions

### ISSUE THREAD

**Issue by kokyhin** [phuoc-ng/react-pdf-viewer#265]
Would be nice to have direct access to functions like search, navigate, download.
Is there any plan to make them accessible ?

**Comment by phuoc-ng** [comment]
There're two approaches:

1) Using the `render-props` (already supported):
See https://react-pdf-viewer.dev/examples/render-props

2) v2.0.0: This approach is being implemented, and almost features are implemented as separate plugins.
So you can built your own plugin or re-use existing plugins which provide given functionality.

For example, you can create
- an external button to download the document with the [download plugin](https://github.com/phuoc-ng/react-pdf-viewer/tree/master/packages/rpv-download).
- an external button to open a document from local with the [open plugin](https://github.com/phuoc-ng/react-pdf-viewer/tree/master/packages/rpv-open)

All current features of v1.7.0 are already implemented as plugins.
Here is the list https://github.com/phuoc-ng/react-pdf-viewer/tree/master/packages

**Comment by kokyhin** [comment]
@phuoc-ng `render-props` is not enough for our needs.

Plugins approach will be available only in `v2.0.0` ? (because right now as i can see it not supported).
When do you plan to release v2.0.0 ?

**Comment by phuoc-ng** [comment]
> Plugins approach will be available only in `v2.0.0`

Yes.

> When do you plan to release v2.0.0 ?

Hopefully in this month. I am testing the developing version (all features are implemented).
