### ISSUE TITLE
PDF doesn't scroll in IE11

### ISSUE THREAD

**Issue by jpproverbio** [phuoc-ng/react-pdf-viewer#50]
Is IE11 fully supported? I found that the viewer doesn't present the scroll properly when it requires to scroll in the page. It works fine in Chrome, Edge, Firebox and Safari.

![IE11_not_scroll](https://user-images.githubusercontent.com/59937763/76037537-32d42900-5fac-11ea-9697-03ab584bdaad.png)

**Comment by phuoc-ng** [comment]
It's never easy to deal with IE 11 :)
I'll try it myself and get back to you.

**Comment by phuoc-ng** [comment]
@jpproverbio With #52 get merged, most of the features work in IE 11.

**Comment by phuoc-ng** [comment]
Updated: The print functionality works in IE 11 with #53.

**Comment by jpproverbio** [comment]
@phuoc-ng Thank you!

**Comment by jpproverbio** [comment]
@phuoc-ng I downloaded v.1.3.0 but the IE11 issue is still happening.

**Comment by phuoc-ng** [comment]
@jpproverbio Stay tuned. It was fixed, but [not released yet](https://github.com/phuoc-ng/react-pdf-viewer/blob/master/CHANGELOG.md#v140-not-released-yet).

The new version v1.4.0 will be released tomorrow.
I'll ping you here when it's available.

**Comment by jpproverbio** [comment]
@phuoc-ng Great thank you for the heads up.

**Comment by phuoc-ng** [comment]
@jpproverbio The v1.4.0 is released.
Please follow [this guide](https://react-pdf-viewer.dev/examples/support-internet-explorer-11) if you want to support IE 11.

**Comment by jpproverbio** [comment]
Thank you @phuoc-ng. I can confirm it's fixed. In our case we use core-js may be a better option than es6-slim if you would like to consider.
