### ISSUE TITLE
Expose methods that can be called from outside

### ISSUE THREAD

**Issue by phuoc-ng** [phuoc-ng/react-pdf-viewer#56]

**Comment by phuoc-ng** [comment]
Example is available [here](https://github.com/phuoc-ng/react-pdf-viewer/blob/master/demo/latest/src/RenderPropsExample.tsx)

**Comment by iksent** [comment]
Your link is not working now (https://github.com/phuoc-ng/react-pdf-viewer/blob/master/demo/latest/src/RenderPropsExample.tsx)

**Comment by phuoc-ng** [comment]
@iksent I'm sorry. It was moved to [another folder](https://github.com/phuoc-ng/react-pdf-viewer/blob/master/demo/render-props/RenderPropsExample.tsx)

**Comment by phuoc-ng** [comment]
The live demo is here https://react-pdf-viewer.dev/examples/render-props

**Comment by iksent** [comment]
It will be much more convenient to use methods with refs.
