### ISSUE TITLE
Add custom layer to each page

### ISSUE THREAD

**Issue by phuoc-ng** [phuoc-ng/react-pdf-viewer#73]
Some use cases:
- Add a water mask
- Don't display the text layer
- Don't render the content for given page
- Select text and do something
- Drag/drop image/canvas

**Comment by phuoc-ng** [comment]
[Watermark example](https://github.com/phuoc-ng/react-pdf-viewer/blob/master/demo/latest/src/WaterMarkExample.tsx):

<img width="1056" alt="Screen Shot 2020-03-14 at 14 40 52" src="https://user-images.githubusercontent.com/57786711/76677610-c340e800-6602-11ea-8305-e3df6ac1d6e4.png">

**Comment by QuantumZer0** [comment]
It would be great if adding Images and Text (Drag) over the PDF is an option. Save and download the modified PDF.

**Comment by phuoc-ng** [comment]
Done. v1.5.0 is released.

**Comment by filetovoid** [comment]
You can download the modified PDF with the watermark? @phuocng
