### ISSUE TITLE
Possibility to use absolute url path ?

### ISSUE THREAD

**Issue by JSurquin** [phuoc-ng/react-pdf-viewer#84]
Hi everyone , everything is in title , there is a possibility to use absolute url path in fileUrl props? 

Because i read the docs and i don't see mention of this 

Thanks for the response

**Comment by phuoc-ng** [comment]
Hi @JSurquin 
It's possible as long as the remote server (which contains the file) allows current server to access the file (due to the cross domain issue).

**Comment by JSurquin** [comment]
Hi @phuoc-ng thanks for your fast response in this subject and the work accomplished for this project

I made a test with Codesanbox with a really small demo 
Here => https://codesandbox.io/s/react-pdf-viewer-react-1612-81ek3

When i use a simple link to sample pdf i have an error like in Codesanbox

Effectively i understand the cross domain issue, but i see others pdf viewer in React or vanilla js can use this link (in codeSanbox , i share the link below too)

http://www.africau.edu/images/default/sample.pdf

I'm just wondering how does this work :)

**Comment by phuoc-ng** [comment]
Thank you! I'll take a look at the demo.

**Comment by phuoc-ng** [comment]
@JSurquin 
Under the hood, the viewer uses the pdf.js API to load and parse the PDF document.
According to the code and the [examples](https://mozilla.github.io/pdf.js/examples/)

> // If absolute URL from the remote server is provided, configure the CORS
> // header on that server.

The following examples work

~~~ javascript
<Viewer
   fileUrl="https://raw.githubusercontent.com/mozilla/pdf.js/ba2edeae/examples/learning/helloworld.pdf"
/>
~~~

<img width="1048" alt="Screen Shot 2020-03-29 at 09 52 31" src="https://user-images.githubusercontent.com/57786711/77838970-070b2400-71a3-11ea-8875-218a6a639887.png">

~~~ javascript
<Viewer
   fileUrl="https://raw.githubusercontent.com/mozilla/pdf.js/ba2edeae/web/compressed.tracemonkey-pldi-09.pdf"
/>
~~~

<img width="1056" alt="Screen Shot 2020-03-29 at 09 53 27" src="https://user-images.githubusercontent.com/57786711/77838981-299d3d00-71a3-11ea-9ba6-fd87fced7128.png">

It makes sense. I can't think of another way to support the remote file.
