### ISSUE TITLE
SVG layer

### ISSUE THREAD

**Issue by phuoc-ng** [phuoc-ng/react-pdf-viewer#89]
Add new SVG layer which can be used to replace the canvas layer

~~~ javascript
const renderPage = (props: RenderPageProps) => {
    return (
        <>
            {props.svgLayer.children}
            {props.textLayer.children}
            {props.annotationLayer.children}
        </>
    );
};

<Viewer
    fileUrl='/path/to/document.pdf'
    renderPage={renderPage}
/>
~~~

<img width="1278" alt="Screen Shot 2020-03-29 at 15 09 44" src="https://user-images.githubusercontent.com/57786711/77844294-c544a280-71cf-11ea-92ab-6e3bfc57ce56.png">

**Comment by JSurquin** [comment]
hi @phuoc-ng , news for this fantastic feature ? :D 

The canvas have a bad resolution in unzoom where the svg would be a perfect choice

**Comment by phuoc-ng** [comment]
@JSurquin 
It's already done (See the PR #90), and will be available in the next big release v1.5.0.
Here is the [example code](https://github.com/phuoc-ng/react-pdf-viewer/blob/master/demo/latest/src/SvgLayerExample.tsx).

**Comment by JSurquin** [comment]
I pull the project and build to a codeSanbox project , is perfect for see difference between canvas and svg

https://codesandbox.io/s/pdf-reader-svg-test-93olo?file=/src/App.js

Good Job 👍

**Comment by phuoc-ng** [comment]
Done. v1.5.0 is released.
