### ISSUE TITLE
PDF viewer stuck on loading and never send request to url specified.

### ISSUE THREAD

**Issue by mahaveer0496** [phuoc-ng/react-pdf-viewer#94]
I'm checking out the library before buying the license but i cant seem to getting it working in my app.

This is my code, this same code when tested in Codesandbox works fine, but when i add this code to my application, there are no requests made to the `fileURL`, `onDocumentLoad` never fires.

There are no CORS error either, i've checked multiple times. In network panel there's just  no requests made to specified URL. No errors thrown either.

Is there no `onError` to check to see what went wrong?

```js
<Worker workerUrl="https://unpkg.com/pdfjs-dist@2.2.228/build/pdf.worker.min.js">
      <div style={{ height: window.innerHeight }}>
        <Viewer
          defaultScale={1}
          onDocumentLoad={console.info}
          fileUrl="https://res.cloudinary.com/dzpcxb0i9/image/upload/v1585215353/20131231103232738561744_mnzsun.pdf"
          initialPage={0}
        />
      </div>
    </Worker>
```

Thanks in advance!

**Comment by phuoc-ng** [comment]
@mahaveer0496 Can you tell me know the version of `pdfjs-dist`?
(You can take a look at `node_modules/pdfjs-dist/package.json`).

~~~ json
{
  "name": "pdfjs-dist",
  "version": "2.3.200",
  "main": "build/pdf.js",
}
~~~

And make sure that version is the same as the worker (2.3.200 in this example):

~~~ javascript
<Worker workerUrl="https://unpkg.com/pdfjs-dist@2.3.200/build/pdf.worker.min.js">
...
</Worker>
~~~

**Comment by mahaveer0496** [comment]
In root package.json
```
"pdfjs-dist": "2.2.228",
"@phuocng/react-pdf-viewer": "1.4.0",
```

in `node_modules/pdfjs-dist/package.json`
```
"name": "pdfjs-dist",
"version": "2.2.228",
```
and workerURL `"https://unpkg.com/pdfjs-dist@2.2.228/build/pdf.worker.min.js"`

All are `2.2.228`, there's no error in console CORS/Version mismatch etc, there's just no request being made and pdf-viewer stays in loading state. @phuoc-ng

**Comment by mahaveer0496** [comment]
upgraded to pdfjs-dist, worker to  `2.3.200` and things are working. 

Thanks for your time @phuoc-ng

**Comment by phuoc-ng** [comment]
I think I should update the guide on official website.

**Comment by phuoc-ng** [comment]
The [official guide](https://react-pdf-viewer.dev/docs/getting-started) is updated. All the docs now use the 2.3.200 version.

Let me know if you need anything else, @mahaveer0496. Looking forward to the purchase :)

**Comment by mahaveer0496** [comment]
Awesome, just 1 more issue, PDFs are blurred, or dont show text at all in Brave browser, Google app mobile.
Here's a sandbox https://codesandbox.io/s/brave-jennings-168x9

If you could take a look please.

Lemme know if i should move this question to new issue. 

Thanks you so much!

**Comment by phuoc-ng** [comment]
@mahaveer0496 Thanks for reporting the issue. I create a new issue (#95) to track it.
