### ISSUE TITLE
initialPage is not working in react-pdf-viewer

### ISSUE THREAD

**Issue by yawar-33** [phuoc-ng/react-pdf-viewer#96]
My code is below
`<Viewer fileUrl="File Path" initialPage={2}/>`

When document loaded it start from index but I want to load it from entered page in previous react js component or from 2.
let me know how to fix this
Thanks

**Comment by phuoc-ng** [comment]
Does [this example](https://react-pdf-viewer.dev/examples/set-the-initial-page) work on your brower?

**Comment by yawar-33** [comment]
> Does [this example](https://react-pdf-viewer.dev/examples/set-the-initial-page) work on your brower?

**Comment by yawar-33** [comment]
it is fixed when I downgrade my package to this version  npm install @phuocng/react-pdf-viewer@1.4.0......
what if I enter range of page link 1-3 then how initial-Page parameter will handle this... is there any fun implemented

**Comment by phuoc-ng** [comment]
@yawar-33 
* The `initialPage` option must be a number. It doesn't support kind of `toolbarSlot.currentPageInput + 2`.

* What is your browser that causes the example https://react-pdf-viewer.dev/examples/set-the-initial-page not working?

**Comment by yawar-33** [comment]
@phuoc-ng 
I am using Google Chrome
Version 80.0.3987.163 (Official Build) (64-bit).
If I input initiallPage={1-3} or {1,3} it is opening from index page not my mention.

**Comment by phuoc-ng** [comment]
> If I input initiallPage={1-3} or {1,3} 

It's not correct set. Please use `initiallPage={1}`, `initiallPage={2}`, or `initiallPage={3}`
