### ISSUE TITLE
force select SelectionMode.Hand on launch 

### ISSUE THREAD

**Issue by JSurquin** [phuoc-ng/react-pdf-viewer#97]
Hi , my question is simple

Can we force select the SelectionMode.Hand on launch component ? 

Actually i create my own render for manipulate RenderViewProps
I use an useEffect in render to accomplish them

Example 
-------------------------------------------

```
const render = (RenderViewerProps) => {

  useEffect(() => {
    RenderViewerProps.changeSelectionMode(SelectionMode.Hand);
  }, [])

}
```
-------------------------------------------

It works , but i have a eslint warning in my terminal , i can't (he warning this) use useEffect in render function (logic) 

my problem is that : how use RenderViewerProps in high order component ? i would use RenderViewProps in my pdf component 

Example 

```
const Pdf = (props) => {

useEffect(() =>  {
    RenderViewerProps.changeSelectionMode(SelectionMode.Hand);
})

// don't work => RenderViewerProps is undefined (all the rest off the line same)

const render = (RenderViewerProps) => {
// My render
}

  return (
    <div>
      <Worker workerUrl="https://unpkg.com/pdfjs-dist@2.2.228/build/pdf.worker.min.js">
        <div>
          <Viewer render={render}  fileUrl={exampleImage}/>
        </div>
      </Worker>
    </div>
  );

}

```

If i had time on this day i create a Codesanbox if needed

Thanks for the time to read this :)

**Comment by phuoc-ng** [comment]
@JSurquin 
Does [this option](https://react-pdf-viewer.dev/docs/options) answer your question?

~~~ javascript
import Viewer, { SelectionMode } from '@phuocng/react-pdf-viewer';

<Viewer
    fileUrl="/path/to/document.pdf"
    selectionMode={SelectionMode.Hand}
/>
~~~

**Comment by JSurquin** [comment]
How ! Really Sorry :') i read the doc many times but I passed by :/, i have a another question but not for the same warning/error , can i create a other issue or just contact you ? :)

**Comment by JSurquin** [comment]
Thank you, that's the right answer 

Really sorry for wasting your time :)

I close the issue

![image](https://user-images.githubusercontent.com/33385043/78875673-8d025700-7a4e-11ea-86e6-3b92b760c668.png)

**Comment by phuoc-ng** [comment]
No problem, @JSurquin.
Feel free to ask more questions by creating more issues. You can drop me an email if it's urgent.
