### ISSUE TITLE
annotation displays bug ? 

### ISSUE THREAD

**Issue by JSurquin** [phuoc-ng/react-pdf-viewer#98]
Hi , i test to create annotation in a simple pdf i have with atril linux (my pdf reader on Ubuntu 18.04)
It works and i have make a test to view if annotation(s) display on reader-pdf 

Yes its works , but i have a strange behaviour 

I put screen capture 

![Sélection_223](https://user-images.githubusercontent.com/33385043/78874923-6bed3680-7a4d-11ea-9dc6-083008bc7bda.png)

![Sélection_225](https://user-images.githubusercontent.com/33385043/78874957-75769e80-7a4d-11ea-8c23-51e869539a14.png)

src="annotation-note.svg" not found on project 

Thanks for reading :)

**Comment by phuoc-ng** [comment]
Can you give me the PDF file, so I can test and fix the issue?

**Comment by JSurquin** [comment]
[sample.pdf](https://github.com/phuoc-ng/react-pdf-viewer/files/4455703/sample.pdf)

Thanks :)

**Comment by phuoc-ng** [comment]
I can confirm that it's a bug. Will fixed with #100

**Comment by phuoc-ng** [comment]
@JSurquin The v1.6.0 is just [released](https://react-pdf-viewer.dev/updates).
Please upgrade to get the annotation bug fixed.

**Comment by JSurquin** [comment]
Hi , i test annotation with the same file that I mentioned above and i don't have any annotation now  

![annotation](https://user-images.githubusercontent.com/33385043/83776078-0c478c00-a688-11ea-8968-5ea58c7cdaf7.gif)

**Comment by JSurquin** [comment]
can you reopen this issue ?

**Comment by phuoc-ng** [comment]
I used the file _sample.pdf_ above, and drag it to the main viewer at https://react-pdf-viewer.dev.
It works as expected:

<img width="1057" alt="Screen Shot 2020-06-07 at 10 15 02" src="https://user-images.githubusercontent.com/57786711/83959515-ded92900-a8a7-11ea-8d16-54ed8844f346.png">

**Comment by JSurquin** [comment]
Hi, I created a quick codesanbox by following the documentation to the letter and I have this error on codesanbox, I wanted to test from scratch to understand where the problem could come from

https://codesandbox.io/s/react-pdf-viewer-160-n5ix4?file=/src/App.js:230-262

![image](https://user-images.githubusercontent.com/33385043/84510255-30791d80-acc5-11ea-8260-10d58044134f.png)

**Comment by JSurquin** [comment]
I just forget to update the css, issue close

**Comment by phuoc-ng** [comment]
Thank you, @JSurquin 👍
