### ISSUE TITLE
Store the currentPage in hooks

### ISSUE THREAD

**Issue by JSurquin** [phuoc-ng/react-pdf-viewer#99]
Hi , sorry in advance for asking lot of questions , i test to store the number of the currentPage in useState Hooks to keep them for the user 

(if user change page (exit to /reader to go /learning (with Router not refresh his page or in new tab) for example) => change the initial page in reader to currentPage viewed by user if return in /reader)

**Example** 

```
const pdf = () => {

const [currentPageNumber , setCurrentPageNumber] = UseState();

const renderToolbar = (toolbarSlot) => {
          {toolbarSlot.currentPage ? setCurrentPageNumber(toolbarSlot.currentPage) : null}
}

  const layout = (
    isSidebarOpened,
    container,
    main,
    toolbar,
    sidebar,
  ) => {
    return defaultLayout(
      isSidebarOpened,
      container,
      main,
      toolbar(renderToolbar),
      sidebar,
    );
  };

console.log(currentPageNumber + 1)

return (
          <Viewer layout={layout} fileUrl={imageExample}/>
)
}
```

This works,
I can update the state of currentPageNumber with call the method in renderToolbar , but i have a eslint warning because it's just a bad thing to update component from inside the function body of different component

this error loop every time i change / scroll page (logic , is call the setCurrentPageNumber method)

![image](https://user-images.githubusercontent.com/33385043/78888533-140cfa80-7a62-11ea-8701-21acf2a6f321.png)

Maybe i don't understand or need more logic to get around this error to store in state in pdf component

**Comment by JSurquin** [comment]
I use a localStorage. 

with LocalStorage.setItem('CurrentPage', toolbarSlot.currentPage) , i don't have this warning and i can use useEffect in pdf.js to set CurrentPage in UseState if localStorage.getItem('CurrentPage') exist , and use this to set initialPage if exist.

**Comment by phuoc-ng** [comment]
`localStorage` is a good, simple solution if you want to persist the page number in this use case.
Can I close the issue?

**Comment by JSurquin** [comment]
Yes you Can :)
